### ISSUE TITLE
Add encrypted key in .travis, to upload files to GitHub

### ISSUE THREAD

**Issue by giordano** [giordano/GSLBuilder.jl#2]
BinaryBuilder's wizard failed to create the encrypted key to be added to the .travis script.  Trying to manually call `obtain_secure_key` hangs forever (*update*: at least for half an hour now)
```julia
julia> BinaryBuilder.obtain_secure_key(Base.stdout, token, gr)
Asking travis to sync github and waiting until it knows about our new repo.
This may take a few seconds (or minutes, depending on Travis' mood)
Still Waiting...
Still Waiting...
Still Waiting...
[infinity many more of them....]
```

Any hint about hot to do this would be much welcome.

**Comment by staticfloat** [comment]
Hmmm, that's annoying.  It's possible that is a Travis problem and not our problem though.  Have you logged in to Travis and verified that it has synced your account?  (E.g. log in to https://travis-ci.org/account/repositories and ensure that your builder repository is listed there).  We do have to wait until Travis has synced the repositories, and we have no control over how long that might take.

**Comment by giordano** [comment]
Yes, the repo was listed on Travis yesterday already, I had a build: https://travis-ci.org/giordano/GSLBuilder.jl

**Comment by giordano** [comment]
Ok, fixed.  Maybe I was trying something wrong before.  For the record, the steps to obtain the key were:

* obtain the token with
    ```julia
    token = BinaryBuilder.obtain_token(Base.stdout, Base.stdin, "GSLBuilder.jl", "giordano")
    ```
    This can be done also on GitHub (https://github.com/settings/tokens) if the token is already there, you can regenerate it

* obtain the secure key with:
    ```julia
    BinaryBuilder.obtain_secure_key(Base.stdout, token, GitHub.Repo("giordano/GSLBuilder.jl"))
    ```
